server:
  port: 446

spring:
  application:
    name: web-service

  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    non-secure-port: ${server.port:80}
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    register-with-eureka: true


noEruakeHttpServer:
  adder: "localhost:30002"