apiVersion: v1
kind: ConfigMap
metadata:
  name: web-service-config
data:
    application.yml: |
    spring.application.name: web-service
    server.port: "446"
   
    eureka.client.service-url.defaultZone: http://erueka-server.demo.svc.cluster.local:8761/eureka/
    eureka.instance.instance-id: web-server:30001

    logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
    info.app.encoding: UTF-8
    info.app.java.source: "1.8"
    info.app.java.traget: "1.8"
    info.app.name: grpc-consumer-erueka

    noEruakeHttpServer.adder: grpc-consumer.demo.svc.cluster.local:30002
