apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-consumer-erueka-config
data:
    application.yml: |
    MYSQL_DB_HOST: mysqldb.demo.svc.cluster.local
    spring.application.name: grpc-consumer-erueka
    spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
    spring.datasource.driver-class-name: com.mysql.jdbc.Driver
    spring.datasource.url: jdbc:mysql://mysqldb.demo.svc.cluster.local:3306/test?useUnicode=true&characterEncoding=utf-8
    spring.datasource.username: root
    spring.datasource.password: abcdef

    spring.datasource.jpa.database : mysql

    eureka.client.service-url.defaultZone: http://erueka-server.demo.svc.cluster.local:8761/eureka/
    eureka.instance.instance-id: grpc-consumer-erueka:30001

    logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
    info.app.encoding: UTF-8
    info.app.java.source: "1.8"
    info.app.java.traget: "1.8"
    info.app.name: grpc-consumer-erueka

    grpcserver.host: grpc-provider.demo.svc.cluster.local
    grpcserver.port: "50052"
