apiVersion: v1
kind: Service
metadata:
  name: grpc-provider
  labels:
    app: grpc-provider
    service: grpc-provider
spec:
  ports:
  - port: 50052
    name: grpc-provider
  selector:
    app: grpc-provider
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-provider
  labels:
    app: grpc-provider
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-provider
      version: v1
  template:
    metadata:
      labels:
        app: grpc-provider
        version: v1
    spec:
      containers:
      - name: grpc-provider
        image: test.cargo.io/demo/go-grpc-provider:0.3
        imagePullPolicy: IfNotPresent
        command: ["/home/demo/src/server/main"]
        #args: ["/home/demo/src/main"]
        env:
          - name: GRPC_SERVER_ADDR
            value: 127.0.0.1:50052
          - name: URL3th
            value: https://jsonplaceholder.typicode.com/posts/1
          - name: URL_BACK
            value: http://grpc-consumer.demo.svc.cluster.local:30001/db/loop  
                    -          
        ports:
        - containerPort: 50052
