apiVersion: v1
kind: Service
metadata:
  name: grpc-consumer-erueka
  labels:
    app: grpc-consumer-erueka
    service: grpc-consumer-erueka
spec:
  ports:
  - port: 30001
    name: grpc-consumer-erueka
  selector:
    app: grpc-consumer-erueka
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-consumer-erueka
  labels:
    app: grpc-consumer-erueka
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-consumer-erueka
      version: v2
  template:
    metadata:
      labels:
        app: grpc-consumer-erueka
        version: v2
    spec:
      containers:
      - name: grpc-consumer-erueka
        image: test.cargo.io/demo/grpc-springboot-servers:0.2
        imagePullPolicy: IfNotPresent
        command: ["java"]
        args: ["-jar","//home/grpc-spring-cloud-consumer/target/grpc-spring-cloud-consumer-1.0-SNAPSHOT.jar"]
        envFrom:
          - configMapRef:
              name: grpc-consumer-erueka-config
        ports:
        - containerPort: 30001
